name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  Enviornment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm i -g @angular/cli
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: ng build  
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Display structure of downloaded files is
      run: ls -R
